QUIZ_DATA = [
    {
        "image": "quiz_1",
        "question": "What is the result of this code?",
        "options": ["ValueError", "15", "TypeError", "510"],
        "correct": "15",
    },
    {
        "image": "quiz_2",
        "question": "What is the result of this code?",
        "options": ["5 10", "20 10", "20 20", "10 10"],
        "correct": "20 20",
    },
    {
        "image": "quiz_3",
        "question": "What is the result of this code?",
        "options": ["3", "2", "1", "TypeError"],
        "correct": "2",
    },
    {
        "image": "quiz_4",
        "question": "What is the result of this code?",
        "options": ["Equal", "Not equal", "False", "TypeError"],
        "correct": "Equal",
    },
    {
        "image": "quiz_5",
        "question": "What is the result of this code?",
        "options": ["static", "class", "static class", "Error"],
        "correct": "class",
    },
    {
        "image": "quiz_6",
        "question": "What is the result of this code?",
        "options": ["ello", "IndexError", "Hello", "H"],
        "correct": "ello",
    },
    {
        "image": "quiz_7",
        "question": "What is the result of this code?",
        "options": ["thon", "Sill", "noht", "ytho"],
        "correct": "noht",
    },
    {
        "image": "quiz_8",
        "question": "What is the result of this code?",
        "options": ["<class 'tuple_iterator'>", "<class 'set_iterator'>", "<class 'list_iterator'>", "TypeError"],
        "correct": "<class 'set_iterator'>",
    },
    {
        "image": "quiz_9",
        "question": "What is the result of this code?",
        "options": ["Nothing to print", "OK", "None", "TypeError"],
        "correct": "Nothing to print",
    },
    {
        "image": "quiz_10",
        "question": "What is the result of this code?",
        "options": ["IndexError", "3", "4", "[3, 4]"],
        "correct": "3",
    },
    {
        "image": "quiz_11",
        "question": "What is the result of this code?",
        "options": ["AttributeError", "10", "5", "TypeError"],
        "correct": "10",
    },
    {
        "image": "quiz_12",
        "question": "What is the result of this code?",
        "options": ["Confused?", "Try again.", "Pythonic!", "SyntaxError"],
        "correct": "Pythonic!",
    },
    {
        "image": "quiz_13",
        "question": "What is the result of this code?",
        "options": ["8", "6", "7", "SyntaxError"],
        "correct": "7",
    },
    {
        "image": "quiz_14",
        "question": "What is the result of this code?",
        "options": ["[3, 5, 'b']", "[5, 3, 'b']", "['b', 3, 5]", "TypeError"],
        "correct": "TypeError",
    },
    {
        "image": "quiz_15",
        "question": "What is the result of this code?",
        "options": ["Hello-my-name-is-Python-", "H-e-l-l-o-m-y-n-a-m-e-i-s-P-y-t-h-o-n-",
                    "H-e-l-l-o- -m-y- -n-a-m-e- -i-s- -P-y-t-h-o-n-", "TypeError"],
        "correct": "H-e-l-l-o-m-y-n-a-m-e-i-s-P-y-t-h-o-n-",
    },
    {
        "image": "quiz_16",
        "question": "What is the result of this code?",
        "options": ["0.636", "0.636'", "0.637", "0.64"],
        "correct": "0.636",
    },
    {
        "image": "quiz_17",
        "question": "What is the result of this code?",
        "options": ["[3, 7, 10]", "[3, 10]", "[3, 7, 9, 10]", "[3, 9, 10]"],
        "correct": "[3, 9, 10]",
    },
    {
        "image": "quiz_18",
        "question": "What is the result of this code?",
        "options": ["12", "1", "7", "TypeError"],
        "correct": "12",
    },
    {
        "image": "quiz_19",
        "question": "What is the result of this code?",
        "options": ["[6, 8]", "[2, 4, 6, 8]", "[4, 6, 8]", "TypeError"],
        "correct": "[4, 6, 8]",
    },
    {
        "image": "quiz_20",
        "question": "What is the result of this code?",
        "options": ["5", "AttributeError", "None", "TypeError"],
        "correct": "TypeError",
    },
]
